name: copilot-build-memorypipeline

on:
  workflow_call:

permissions:
  contents: read

jobs:
  memorypipeline:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { dotnet: "10.0", configuration: Release, os: ubuntu-latest }

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Find solutions
        shell: bash
        run: echo "SOLUTIONS=$(find ./ -type f -name "*.sln" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Restore dependencies
        shell: bash
        run: |
          for solution in ${{ env.SOLUTIONS }}; do
            dotnet restore $solution
          done

      - name: Build memorypipeline
        shell: bash
        run: |
          dotnet publish memorypipeline/CopilotChatMemoryPipeline.csproj --configuration ${{ matrix.configuration }} --output ./memorypipeline/publish

      - name: Package memorypipeline
        shell: bash
        run: |
          cd memorypipeline/publish
          zip -r ../../memorypipeline.zip .

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: memorypipeline
          path: ./memorypipeline.zip

